development:
  adapter: postgresql
  encoding: unicode
  database: somnang_development
  pool: 5
  username: radinreth
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: somnang_test
  pool: 5
  username: radinreth
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: somnang_production
  pool: 5
  username: radinreth
  password: